### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by Chapp1eee** [AlizerUncaged/waifu-desktop#1]
Hey

After launching Waifu.exe, the program is stuck at "Welcome Back! checking Puppeteer". and just doesn't progress.

I have set up the APIs in the settings.

**Comment by Yaekirua** [comment]
i got same issue

**Comment by MagicDanielle** [comment]
same

**Comment by Mrciller** [comment]
i downloaded the latest version, and it still gets stuck in Checking Puppeteer
